# Generated by Django 3.1.2 on 2020-10-21 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rubro', models.CharField(max_length=50)),
                ('codigo_subrubro', models.CharField(max_length=50)),
                ('codigo_articulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio_compra', models.FloatField()),
                ('rubro', models.CharField(max_length=50)),
                ('subrubro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=6, verbose_name='Sexo')),
                ('telefono', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('cuil_cuit', models.IntegerField()),
                ('categoria_iva', models.CharField(choices=[('Autonomo', 'Autonomo'), ('Particular', 'Particular')], max_length=15, verbose_name='Categoria Iva')),
                ('cuenta_contable', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=50)),
                ('precio_max', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BAapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=6, verbose_name='Sexo')),
                ('telefono', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('fax', models.CharField(max_length=50)),
                ('cuil_cuit', models.IntegerField()),
                ('codigo_cta', models.IntegerField()),
                ('saldo_inicial', models.FloatField()),
                ('alicuota', models.FloatField()),
                ('desde_iibb', models.FloatField()),
                ('hasta_iibb', models.FloatField()),
                ('moneda', models.CharField(max_length=50)),
                ('numero_cai', models.IntegerField()),
                ('vencimiento_cai', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=6, verbose_name='Sexo')),
                ('telefono', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('comision_usd', models.FloatField()),
                ('comision', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('aceptada', models.BooleanField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BAapp.articulo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BAapp.pedido')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BAapp.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('razon_social', models.CharField(max_length=30)),
                ('total', models.FloatField()),
                ('mes_de_pago', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=300)),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BAapp.propuesta')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BAapp.proveedor'),
        ),
    ]
