# Generated by Django 3.1.2 on 2021-08-22 23:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('ingrediente', models.CharField(max_length=200)),
                ('concentracion', models.CharField(max_length=50, null=True)),
                ('banda_toxicologica', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('VI', 'VI'), ('LA', 'LA'), ('LB', 'LB')], max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad', models.CharField(max_length=50, null=True)),
                ('formulacion', models.CharField(max_length=20, null=True)),
            ],
            options={
                'search_fields': ('marca', 'ingrediente', 'concentracion'),
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_related_name': 'compradores',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50)),
                ('nombre_comercial', models.CharField(blank=True, max_length=50, null=True)),
                ('cuit', models.CharField(blank=True, max_length=14, null=True)),
                ('ingresos_brutos', models.CharField(blank=True, max_length=9, null=True)),
                ('fecha_exclusion', models.DateField(blank=True, null=True)),
                ('categoria_iva', models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('CF', 'Consumidor Final'), ('RIM', 'Responsable Inscripto M'), ('EX', 'Exento'), ('MO', 'Monotributo')], max_length=25, null=True)),
                ('domicilio_fiscal', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'search_fields': ('razon_social', 'nombre_comercial', 'cuit', 'categoria_iva'),
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('numero_factura', models.IntegerField()),
                ('monto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)])),
                ('documento', models.FileField(upload_to='media/facturas/%Y/%m/%d')),
            ],
            options={
                'default_related_name': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Financiacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.BooleanField()),
                ('tasa', models.IntegerField(null=True)),
                ('condicion_comercial', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('tipo_de_negocio', models.CharField(choices=[('VT', 'Venta'), ('CS', 'Consignacion')], max_length=2)),
                ('aprobado', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('HO', 'Hombre'), ('MU', 'Mujer'), ('NB', 'Otro')], max_length=6)),
                ('dni', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ManyToManyField(to='BAapp.Empresa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('lote', models.CharField(max_length=255)),
                ('observaciones', models.TextField()),
                ('documento', models.FileField(upload_to='media/remitos/%Y/%m/%d')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='remitos', to='BAapp.negocio')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='remitos', to='BAapp.proveedor')),
            ],
            options={
                'default_related_name': 'remitos',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('monto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)])),
                ('documento', models.FileField(upload_to='media/recibos/%Y/%m/%d')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.negocio')),
                ('recibe_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('envio_comprador', models.BooleanField()),
                ('visto', models.BooleanField(default=False)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='propuestas', to='BAapp.negocio')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cobrado', models.BooleanField(default=False)),
                ('observaciones', models.CharField(max_length=300)),
                ('visualizacion', models.BooleanField()),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.propuesta')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.telefono'),
        ),
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrdenDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('monto', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)])),
                ('documento', models.FileField(upload_to='media/ordenesPagos/%Y/%m/%d')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.factura')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.negocio')),
                ('recibe_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('documento', models.FileField(upload_to='media/ordenesCompras/%Y/%m/%d')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.negocio')),
                ('recibe_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hyperlink', models.CharField(max_length=255)),
                ('visto', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('tipo_nota', models.CharField(choices=[('CR', 'Credito'), ('DV', 'Devito')], max_length=15)),
                ('documento', models.FileField(upload_to='media/notas/%Y/%m/%d')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas', to='BAapp.negocio')),
            ],
            options={
                'default_related_name': 'notas',
            },
        ),
        migrations.AddField(
            model_name='negocio',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.vendedor'),
        ),
        migrations.CreateModel(
            name='Logistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logisticas', to='BAapp.empresa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logisticas', to='BAapp.persona')),
            ],
            options={
                'default_related_name': 'logisticas',
            },
        ),
        migrations.CreateModel(
            name='ItemPropuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_venta', models.FloatField(blank=True, null=True)),
                ('precio_compra', models.FloatField(blank=True, null=True)),
                ('divisa', models.CharField(blank=True, choices=[('AR', 'Pesos'), ('USD', 'Dolar')], max_length=40, null=True)),
                ('destino', models.CharField(default='', max_length=255, null=True)),
                ('fecha_entrega', models.CharField(blank=True, max_length=12, null=True)),
                ('aceptado', models.BooleanField()),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_real_pago', models.DateTimeField(blank=True, null=True)),
                ('tasa', models.CharField(blank=True, choices=[(None, 'Elija tasa'), ('0', '0%'), ('0.3', '0.3%'), ('0.4', '0.4%'), ('0.5', '0.5%'), ('0.6', '0.6%'), ('0.7', '0.70%'), ('0.75', '0.75%'), ('0.85', '0.85%'), ('1', '1.00%'), ('2', '2.00%'), ('2.5', '2.50%'), ('2.75', '2.75%'), ('3', '3.00%'), ('3.5', '3.50%'), ('3.6', '36.00%'), ('inc', 'INCLUIDA')], max_length=15, null=True)),
                ('fecha_salida_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_real_entrega', models.DateTimeField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.articulo')),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='BAapp.propuesta')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.proveedor')),
                ('tipo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.tipopago')),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gerentes', to='BAapp.empresa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gerentes', to='BAapp.persona')),
            ],
            options={
                'default_related_name': 'gerentes',
            },
        ),
        migrations.CreateModel(
            name='FacturaComision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('documento', models.FileField(upload_to='media/facturasComision/%Y/%m/%d')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='facturas_comisiones', to='BAapp.negocio')),
                ('recibe_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='facturas_comisiones', to='BAapp.proveedor')),
            ],
            options={
                'default_related_name': 'facturas_comisiones',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='facturas', to='BAapp.negocio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='facturas', to='BAapp.proveedor'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_pago',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='facturas', to='BAapp.tipopago'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='retenciones',
            field=models.ManyToManyField(to='BAapp.Retencion'),
        ),
        migrations.CreateModel(
            name='DomicilioPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domicilio', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.domicilio')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domicilios_postal', to='BAapp.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DomicilioPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domicilio', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.domicilio')),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domicilio', to='BAapp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('documento', models.FileField(upload_to='media/cuentasCorriente/%Y/%m/%d')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cuentas_corrientes', to='BAapp.negocio')),
            ],
            options={
                'default_related_name': 'cuentas_corrientes',
            },
        ),
        migrations.CreateModel(
            name='ContansiaRentencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('importe', models.FloatField()),
                ('documento', models.FileField(upload_to='media/constanciasRetencion/%Y/%m/%d')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.negocio')),
                ('recibe_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='comprador',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='compradores', to='BAapp.empresa'),
        ),
        migrations.AddField(
            model_name='comprador',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='compradores', to='BAapp.persona'),
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('documento', models.FileField(upload_to='media/cheques/%Y/%m/%d')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cheques', to='BAapp.negocio')),
            ],
            options={
                'default_related_name': 'cheques',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articulos', to='BAapp.empresa'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='administradores', to='BAapp.empresa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='administradores', to='BAapp.persona')),
            ],
            options={
                'default_related_name': 'administradores',
            },
        ),
    ]
