# Generated by Django 3.1.2 on 2020-11-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=6, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='mes_de_pago',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=6, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='vencimiento_cai',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=6, verbose_name='Sexo'),
        ),
    ]
