# Generated by Django 3.1.2 on 2023-01-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='estado',
            field=models.CharField(blank=True, choices=[('NEGOCIACION', 'En Negociación'), ('ESP_CONF', 'Esperando confirmación'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default=None, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('EX', 'Exento'), ('RI', 'Responsable Inscripto'), ('MO', 'Monotributo'), ('CF', 'Consumidor Final'), ('RIM', 'Responsable Inscripto M')], max_length=25, null=True),
        ),
    ]
