# Generated by Django 3.1.2 on 2021-09-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0002_auto_20210907_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='id_de_neg',
            field=models.CharField(default='', max_length=255, verbose_name='Identificador de negocio'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('RIM', 'Responsable Inscripto M'), ('MO', 'Monotributo'), ('CF', 'Consumidor Final'), ('RI', 'Responsable Inscripto'), ('EX', 'Exento')], max_length=25, null=True),
        ),
    ]
