# Generated by Django 3.1.2 on 2023-01-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0002_auto_20230120_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='aprobado',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='cancelado',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('MO', 'Monotributo'), ('RI', 'Responsable Inscripto'), ('EX', 'Exento'), ('RIM', 'Responsable Inscripto M'), ('CF', 'Consumidor Final')], max_length=25, null=True),
        ),
    ]
