# Generated by Django 3.1.2 on 2020-11-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0002_auto_20201106_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='mes_de_pago',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='vencimiento_cai',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
    ]
