# Generated by Django 3.1.2 on 2023-01-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0003_auto_20230120_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negocio',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('CF', 'Consumidor Final'), ('RIM', 'Responsable Inscripto M'), ('EX', 'Exento'), ('MO', 'Monotributo')], max_length=25, null=True),
        ),
    ]
