# Generated by Django 3.1.2 on 2021-08-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0003_auto_20210822_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContansiaRentencion',
            new_name='ConstanciaRentencion',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('EX', 'Exento'), ('RIM', 'Responsable Inscripto M'), ('RI', 'Responsable Inscripto'), ('CF', 'Consumidor Final'), ('MO', 'Monotributo')], max_length=25, null=True),
        ),
    ]
