# Generated by Django 3.1.2 on 2021-09-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0003_auto_20210909_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('EX', 'Exento'), ('CF', 'Consumidor Final'), ('MO', 'Monotributo'), ('RIM', 'Responsable Inscripto M')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='id_de_neg',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Identificador de negocio'),
        ),
    ]
