# Generated by Django 3.1.2 on 2023-03-08 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0004_auto_20230122_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articulos', to='BAapp.empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('CF', 'Consumidor Final'), ('MO', 'Monotributo'), ('RI', 'Responsable Inscripto'), ('EX', 'Exento'), ('RIM', 'Responsable Inscripto M')], max_length=25, null=True),
        ),
    ]
