# Generated by Django 3.1.2 on 2021-09-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0004_auto_20210909_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('RIM', 'Responsable Inscripto M'), ('EX', 'Exento'), ('CF', 'Consumidor Final'), ('RI', 'Responsable Inscripto'), ('MO', 'Monotributo')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='id_de_neg',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Identificador de negocio'),
        ),
    ]
