# Generated by Django 3.1.2 on 2021-10-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0004_auto_20210822_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='id_de_neg',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, null=True, verbose_name='Identificador de negocio'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('RIM', 'Responsable Inscripto M'), ('MO', 'Monotributo'), ('CF', 'Consumidor Final'), ('RI', 'Responsable Inscripto'), ('EX', 'Exento')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='itempropuesta',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BAapp.proveedor'),
        ),
    ]
