# Generated by Django 3.1.2 on 2021-09-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0005_auto_20210909_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('EX', 'Exento'), ('RIM', 'Responsable Inscripto M'), ('CF', 'Consumidor Final'), ('MO', 'Monotributo'), ('RI', 'Responsable Inscripto')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='id_de_neg',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, null=True, verbose_name='Identificador de negocio'),
        ),
    ]
