# Generated by Django 3.1.2 on 2021-11-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0005_auto_20211019_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('MO', 'Monotributo'), ('CF', 'Consumidor Final'), ('RIM', 'Responsable Inscripto M'), ('EX', 'Exento')], max_length=25, null=True),
        ),
    ]
