# Generated by Django 3.1.2 on 2023-03-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0005_auto_20230308_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='estado',
            field=models.CharField(blank=True, choices=[('RECIBIDO', 'Recibido'), ('NEGOCIACION', 'En Negociación'), ('ESP_CONF', 'Esperando confirmación'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default=None, max_length=22, null=True),
            ),
        # ALTER TABLE BAapp_negocio ADD COLUMN estado VARCHAR(22) DEFAULT NULL COMMENT 'Estado del negocio' AFTER id;
    ]
