# Generated by Django 3.1.2 on 2023-04-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0006_auto_20230317_1926'),
    ]

    operations = [
    ]
