# Generated by Django 3.1.2 on 2023-04-19 22:10

from django.db import migrations , models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0006_auto_20230317_1926'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('EX', 'Exento'), ('CF', 'Consumidor Final'), ('MO', 'Monotributo'), ('RIM', 'Responsable Inscripto M')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='itempropuesta',
            name='cantidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
