# Generated by Django 3.1.2 on 2023-04-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0007_auto_20230419_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('CF', 'Consumidor Final'), ('EX', 'Exento'), ('MO', 'Monotributo'), ('RI', 'Responsable Inscripto'), ('RIM', 'Responsable Inscripto M')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itempropuesta',
            name='cantidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
