# Generated by Django 3.1.2 on 2023-04-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0007_auto_20230419_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('CF', 'Consumidor Final'), ('MO', 'Monotributo'), ('RIM', 'Responsable Inscripto M'), ('EX', 'Exento')], max_length=25, null=True),
        ),
    ]
