# Generated by Django 3.1.2 on 2021-09-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0007_auto_20210909_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('RIM', 'Responsable Inscripto M'), ('EX', 'Exento'), ('CF', 'Consumidor Final'), ('MO', 'Monotributo'), ('RI', 'Responsable Inscripto')], max_length=25, null=True),
        ),
    ]
