# Generated by Django 3.1.2 on 2023-05-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0008_auto_20230426_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('CF', 'Consumidor Final'), ('RI', 'Responsable Inscripto'), ('RIM', 'Responsable Inscripto M'), ('MO', 'Monotributo'), ('EX', 'Exento')], max_length=25, null=True),
        ),
    ]
