# Generated by Django 3.1.2 on 2023-06-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0011_auto_20230530_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='id_de_neg',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('EX', 'Exento'), ('CF', 'Consumidor Final'), ('RI', 'Responsable Inscripto'), ('RIM', 'Responsable Inscripto M'), ('MO', 'Monotributo')], max_length=25, null=True),
        ),
    ]
