# Generated by Django 3.1.2 on 2024-01-11 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0012_auto_20230612_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempropuesta',
            old_name='fecha_pago',
            new_name='fecha_pago_str',
        ),
        migrations.AddField(
            model_name='itempropuesta',
            name='fecha_pago_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('MO', 'Monotributo'), ('CF', 'Consumidor Final'), ('RIM', 'Responsable Inscripto M'), ('EX', 'Exento'), ('RI', 'Responsable Inscripto')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='itempropuesta',
            name='tasa',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Tasa Mensual'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='estado',
            field=models.CharField(blank=True, choices=[('RECIBIDO', 'Recibido'), ('NEGOCIACION', 'En Negociación'), ('ESP_CONF', 'Esperando confirmación'), ('CONFIRMADO', 'Confirmado'), ('YA_CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default=None, max_length=22, null=True),
        ),
    ]
