# Generated by Django 3.1.2 on 2024-01-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0013_auto_20240111_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('EX', 'Exento'), ('RI', 'Responsable Inscripto'), ('RIM', 'Responsable Inscripto M'), ('CF', 'Consumidor Final'), ('MO', 'Monotributo')], max_length=25, null=True),
        ),
    ]
