# Generated by Django 3.1.2 on 2024-01-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0014_auto_20240120_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('EX', 'Exento'), ('RI', 'Responsable Inscripto'), ('CF', 'Consumidor Final'), ('MO', 'Monotributo'), ('RIM', 'Responsable Inscripto M')], max_length=25, null=True),
        ),
    ]
