# Generated by Django 3.1.2 on 2024-01-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAapp', '0015_auto_20240121_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempropuesta',
            old_name='fecha_entrega',
            new_name='fecha_entrega_str',
        ),
        migrations.AddField(
            model_name='itempropuesta',
            name='fecha_entrega_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categoria_iva',
            field=models.CharField(blank=True, choices=[('RIM', 'Responsable Inscripto M'), ('CF', 'Consumidor Final'), ('RI', 'Responsable Inscripto'), ('EX', 'Exento'), ('MO', 'Monotributo')], max_length=25, null=True),
        ),
    ]
